# Bootstrap
. $HOME/.zsh/bootstrap.zsh

# Auto update - whi will try to autoupdate configs
[ "$WORKSTATION_AUTOUPDATE" = "true" ] && (wup &> /dev/null &)

# Allow local customizations in the $HOME/.zshrc_local_before file
[ -f $HOME/.zshrc_local_before ] && . $HOME/.zshrc_local_before

# Install zplug
if [ ! -d $ZPLUG_HOME ]; then
  git clone https://github.com/zplug/zplug $ZPLUG_HOME
fi
. $ZPLUG_HOME/init.zsh

# External plugins (initialized before)
. $HOME/.zsh/plugins_before.zsh

# External settings
. $HOME/.zsh/external.zsh

# Aliases
. $HOME/.zsh/aliases.zsh

# Functions
. $HOME/.zsh/functions.zsh

# Custom theme
[ -f "$ZSH_THEME_PATH/$ZSH_THEME.zsh" ] && . "$ZSH_THEME_PATH/$ZSH_THEME.zsh"

# External plugins (initialized after)
. $HOME/.zsh/plugins_after.zsh

# Allow local customizations in the $HOME/.zshrc_local_after file
[ -f $HOME/.zshrc_local_after ] && . $HOME/.zshrc_local_after

[ -f $HOME/.zsh-load/loader.zsh ] && . $HOME/.zsh-load/loader.zsh

[ -f "${HOME}/.iterm2_shell_integration.zsh" ] && . "${HOME}/.iterm2_shell_integration.zsh"

if ! zplug check --verbose; then
  zplug install
fi

zplug load
