#zmodload zsh/zprof

PROFILE_STARTUP=false
if [ "$PROFILE_STARTUP" = "true" ]; then
  # http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html
  PS4=$'%D{%M%S%.} %N:%i> '
  exec 3>&2 2> /tmp/startlog.$$
  setopt xtrace prompt_subst
fi

# Bootstrap
. $HOME/.zsh/bootstrap.zsh

# External plugins (initialized before)
. $HOME/.zsh/plugins_before.zsh

# External settings
. $HOME/.zsh/external.zsh

# Aliases
. $HOME/.zsh/aliases.zsh

# External plugins (initialized after)
. $HOME/.zsh/plugins_after.zsh

# Functions
. $HOME/.zsh/functions.zsh

# Allow local customizations loading ~/.zsh-load folder
if [ -d "$HOME/.zsh-load" ];then
  for TO_LOAD in $HOME/.zsh-load/*
  do
    . $TO_LOAD
  done
fi

[ -f "${HOME}/.iterm2_shell_integration.zsh" ] && . "${HOME}/.iterm2_shell_integration.zsh"

# Auto update - whi will try to autoupdate configs
[ "$WORKSTATION_AUTOUPDATE" = "true" ] && (echo '' > /tmp/wup.log && wup &> /tmp/wup.log &)

# Entirety of my startup file... then
if [[ "$PROFILE_STARTUP" == true ]]; then
  unsetopt xtrace
  exec 2>&3 3>&-
fi
