# Bootstrap
. $HOME/.zsh/bootstrap.zsh

# External plugins (initialized before)
. $HOME/.zsh/plugins_before.zsh

# External settings
. $HOME/.zsh/external.zsh

# Aliases
. $HOME/.zsh/aliases.zsh

# External plugins (initialized after)
. $HOME/.zsh/plugins_after.zsh

# Functions
. $HOME/.zsh/functions.zsh

# Allow local customizations loading ~/.zsh-load folder
if [ -d "$HOME/.zsh-load" ];then
  for TO_LOAD in $HOME/.zsh-load/*
  do
    . $TO_LOAD
  done
fi

# Auto update - whi will try to autoupdate configs
[ "$WORKSTATION_AUTOUPDATE" = "true" ] && (echo '' > /tmp/wup.log && wup &> /tmp/wup.log &)
