- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config', '~/.config/nvim']

- link:
    ~/.agignore: dotfiles/agignore
    ~/.aria2/aria2.conf: dotfiles/aria2.conf
    ~/.config/nvim/init.vim: dotfiles/neovim
    ~/.gitconfig: dotfiles/gitconfig
    ~/.gitignore_global: dotfiles/gitignore_global
    ~/.gnupg/gpg.conf: dotfiles/gpg.conf
    ~/.inputrc: dotfiles/inputrc
    ~/.npmrc: dotfiles/npmrc
    ~/.psqlrc: dotfiles/psqlrc
    ~/.screenrc: dotfiles/screenrc
    ~/.tmux.conf: dotfiles/tmux.conf
    ~/.zsh: dotfiles/zsh
    ~/.zshrc: dotfiles/zshrc

- shell:
  - mkdir -p ~/projects ~/bin ~/.zsh-load
  - git submodule update --init --recursive # after linking ~/.gitconfig
  - npm install --prefix ~/.zsh/plugins/lwd
