- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config', '~/.ipython/profile_default/', '~/.config/nvim']

- link:
    ~/.agignore: agignore
    ~/.aria2/aria2.conf: aria2.conf
    ~/.config/nvim/init.vim: neovim
    ~/.workstation: ''
    ~/.gitconfig: gitconfig
    ~/.gitignore_global: gitignore_global
    ~/.gnupg/gpg.conf: gpg.conf
    ~/.inputrc: inputrc
    ~/.ipython/profile_default/ipython_kernel_config.py: ipython/profile_default/ipython_kernel_config.py
    ~/.npmrc: npmrc
    ~/.psqlrc: psqlrc
    ~/.screenrc: screenrc
    ~/.tmux.conf: tmux.conf
    ~/.zsh: zsh
    ~/.zshrc: zshrc

- shell:
  - mkdir -p ~/.config/nvim/ ~/projects ~/bin ~/.zsh-load
  - git update-submodules # after linking ~/.gitconfig
