- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config', '~/.config/nvim']

- link:
    ~/.agignore: dotfiles/agignore
    ~/.aria2/aria2.conf: dotfiles/aria2.conf
    ~/.config/nvim/init.vim: dotfiles/neovim
    ~/.gnupg/gpg.conf: dotfiles/gpg.conf
    ~/.inputrc: dotfiles/inputrc
    ~/.colordiffrc: dotfiles/colordiffrc
    ~/.npmrc: dotfiles/npmrc
    ~/.psqlrc: dotfiles/psqlrc
    ~/.screenrc: dotfiles/screenrc
    ~/.zsh: dotfiles/zsh
    ~/.zshrc: dotfiles/zshrc
    ~/.tmux.conf: dotfiles/tmux.conf

- shell:
  - touch ~/.gitconfig && grep '.workstation/dotfiles/gitconfig' ~/.gitconfig || echo -e '[include]\n\tpath = ~/.workstation/dotfiles/gitconfig' >> ~/.gitconfig
  - mkdir -p ~/projects ~/bin ~/.zsh-load ~/.autoload-zsh
  - git submodule update --init --recursive --remote --merge # after linking ~/.gitconfig
