# macros
[macros.brew]
  prefix = ['brew', 'install', '-f']

[macros.goget]
  deps = ['golang']
  prefix = ['go', 'get']

[macros.gem]
  deps = ['system_apps']
  prefix = ['gem', 'install']

[macros.clone]
  deps = ['git']
  prefix = ['git', 'clone']

[macros.install__debian]
  prefix = ['sudo', 'apt-get', 'install', '-y']

[macros.install__fedora]
  prefix = ['sudo', 'dnf', '-y', 'install']

[macros.install__osx]
  prefix = ['@brew']

# tasks
[tasks.git]
  rejects = [['which', 'git']]
  cmdspre = [['echo', 'Installing git']]
  cmds = [['@install', 'git']]
  cmdspost = [['echo', 'Installed git!']]

[tasks.n]

  envs = [['N_PREFIX', '${HOME}/.n']]
  rejects = [['test', '-d',  '${N_PREFIX}']]
  cmds = [['curl', '-L', 'https://git.io/n-install', '-o', '/tmp/n-install'], ['bash', '/tmp/n-install']]

[tasks.yarn]
  rejects = [['which', 'yarn']]
  cmds = [['@brew', 'yarn']]
  deps = ['n']

[tasks.golang]
  envs = [['GOPATH', '${HOME}/projects/go']]
  rejects = [['which', 'go']]
  cmdspre = [['echo', 'Installing golang']]
  cmds = [['mkdir', '-p', '$GOPATH'], ['@install', 'golang']]
  cmdspost = [['echo', 'Installed golang!']]

# base tasks
[tasks.gitconfig]
  cmds = [['bash', '${HM_SRC}/utils/gitconfig.sh']]

[tasks.system_apps]
  envs = [['GOPATH', '${HOME}/projects/go']]
  cmdspre = [['echo', 'Installing system_apps'], ['mkdir', '-p', '$GOPATH']]
  cmds = [['@install', 'zsh', 'git', 'curl', 'golang', 'pv', 'bat', 'ruby', 'aria2', 'hub']]
  cmdspost = [['echo', 'Installed system_apps!']]


[tasks.system_apps__fedora]
  deps = ['system_apps__']
  cmdspre = [['chsh', '-s', '/usr/bin/zsh'], ['echo', 'Installing system_apps fedora']]
  cmds = [['@install', 'ruby-devel', 'fd-find']]

[tasks.system_apps__debain]
  deps = ['system_apps__']
  cmdspre = [['chsh', '-s', '/usr/bin/zsh'], ['echo', 'Installing system_apps debian']]
  cmds = [['@install', 'ruby-dev', 'fd-find']]

[tasks.system_apps__osx]
  deps = ['system_apps__']
  cmdspre = [['chsh', '-s', '/bin/zsh'], ['echo', 'Installing system_apps osx']]
  cmds = [['@install', 'fd']]

[tasks.brew_apps]
  cmdspre = [['echo', 'Installing brew apps']]
  cmds = [['@brew', 'tmux', 'ripgrep', 'fzf']]
  cmdspost = [['echo', 'Installed brew apps!']]

[tasks.go_apps]
  cmdspre = [['echo', 'Installing go apps']]
  cmds = [
    ['@goget', '-u', 'github.com/augustoroman/highlight'],
    ['@goget', '-u', 'github.com/arl/gitmux']
  ]

[tasks.ruby_apps]
  cmdspre = [['echo', 'Installing ruby apps']]
  cmds = [
    ['@gem', 'colorls']
  ]

[tasks.base]
  deps = ['system_apps', 'brew_apps', 'go_apps', 'ruby_apps', 'yarn', 'gitconfig']

[tasks.symlinks]
  cmdspre = [['echo', 'Symlinks will be created at', '${HM_DEST}']]
  cmdspost = [['echo', 'Symlinks created (or recreated)!']]
  links = [
    ['.agignore', 'rcfiles/agignore'],
    ['.aria2/aria2.conf', 'rcfiles/aria2.conf'],
    ['.colordiffrc', 'rcfiles/colordiffrc'],
    ['.config/alacritty/alacritty.yml', 'rcfiles/alacritty.yml'],
    ['.config/nvim/init.vim', 'rcfiles/neovim'],
    ['.gnupg/gpg.conf', 'rcfiles/gpg.conf'],
    ['.inputrc', 'rcfiles/inputrc'],
    ['.npmrc', 'rcfiles/npmrc'],
    ['.psqlrc', 'rcfiles/psqlrc'],
    ['.screenrc', 'rcfiles/screenrc'],
    ['.tmux.conf', 'rcfiles/tmux.conf'],
    ['.zsh', 'rcfiles/zsh'],
    ['.zshrc', 'rcfiles/zshrc'],
    ['.zshenv', 'rcfiles/zshenv']
  ]

[tasks.default]
  deps = ['base', 'symlinks']
