# macros
[macros.install__apt]
  prefix = ['sudo', 'apt-get', 'install', '-y']

[macros.install__dnf]
  prefix = ['sudo', 'dnf', '-y', 'install']

[macros.brew]
  prefix = ['brew', 'install', '-f']

[macros.goget]
  deps = ['golang']
  prefix = ['go', 'get']

[macros.clone]
  deps = ['git']
  prefix = ['git', 'clone']

# tasks
[tasks.git]
  rejects = [['which', 'git']]
  cmdspre = [['echo', 'Installing git']]
  cmds = [['@install', 'git']]
  cmdspost = [['echo', 'Installed git!']]

[tasks.n]
  rejects = [['which', 'n']]
  cmds = [['curl', '-K', 'https://git.io/n-install', '-o', '/tmp/n-install'], ['bash', '/tmp/n-install']]

[tasks.yarn]
  rejects = [['which', 'yarn']]
  cmdspre = [['curl', '--location', 'https://dl.yarnpkg.com/rpm/yarn.repo', '-o', '/tmp/yarn-install'], ['sudo', 'cp', '/tmp/yarn-install', '/etc/yum.repos.d/yarn.repo']]
  cmds = [['sudo', 'dnf', 'install', 'yarn']]
  deps = ['n']

[tasks.golang]
  envs = [['GOPATH', '${HM_DEST}/projects/go']]
  rejects = [['which', 'go']]
  cmdspre = [['echo', 'Installing golang']]
  cmds = [['mkdir', '-p', '$GOPATH'], ['@install', 'golang']]
  cmdspost = [['echo', 'Installed golang!']]

# base tasks
[tasks.system_apps]
  envs = [['GOPATH', '${HM_DEST}/projects/go']]
  cmdspre = [['echo', 'Installing system_apps'], ['mkdir', '-p', '$GOPATH']]
  cmds = [['@install', 'zsh', 'git', 'curl', 'golang', 'pv']]
  cmdspost = [['chsh', '-s', '/usr/bin/zsh'], ['echo', 'Installed system_apps!']]

[tasks.brew_apps]
  cmdspre = [['echo', 'Installing brew apps']]
  cmds = [['@brew', 'tmux', 'ripgrep', 'fzf']]
  cmdspost = [['echo', 'Installed brew apps!']]

[tasks.base]
  deps = ['system_apps', 'brew_apps', 'yarn']

[tasks.symlinks]
  cmdspre = [['echo', 'Symlinks will be created at', '${HM_DEST}']]
  cmdspost = [['echo', 'Symlinks created (or recreated)!']]
  links = [
    ['.agignore', 'rcfiles/agignore'],
    ['.aria2/aria2.conf', 'rcfiles/aria2.conf'],
    ['.config/nvim/init.vim', 'rcfiles/neovim'],
    ['.gnupg/gpg.conf', 'rcfiles/gpg.conf'],
    ['.inputrc', 'rcfiles/inputrc'],
    ['.colordiffrc', 'rcfiles/colordiffrc'],
    ['.npmrc', 'rcfiles/npmrc'],
    ['.psqlrc', 'rcfiles/psqlrc'],
    ['.screenrc', 'rcfiles/screenrc'],
    ['.zsh', 'rcfiles/zsh'],
    ['.zshrc', 'rcfiles/zshrc'],
    ['.tmux.conf', 'rcfiles/tmux.conf'],
    ['.config/rofi', 'rcfiles/rofi'],
    ['.Xresources', 'rcfiles/Xresources']
  ]

[tasks.default]
  deps = ['base', 'symlinks']
