#!/usr/bin/env zsh

INPUT_DIR="$1"
BASEDIR=$HOME/.workstation
CLONE_REPO=1
if [ "$INPUT_DIR" != "" ]; then
  BASEDIR=$INPUT_DIR
  shift
fi

if [[ "$@" = *'--skip-clone'* ]]; then
  CLONE_REPO=0
fi

DOTBOT_DIR=".dotbot"
DOTBOT_BIN="bin/dotbot"
CONFIG="${BASEDIR}/.install.conf.yaml"
OS_INSTALLER=$(type brew &> /dev/null && echo "brew install -f" || echo "sudo apt-get install -y")

TO_INSTALL=""

type curl &> /dev/null || TO_INSTALL="$TO_INSTALL curl"
type git &> /dev/null || TO_INSTALL="$TO_INSTALL git"
type zsh &> /dev/null || TO_INSTALL="$TO_INSTALL zsh"

if [ "$TO_INSTALL" != "" ]; then
  echo "Installing '$TO_INSTALL'..." && \
  eval $OS_INSTALLER $TO_INSTALL > /dev/null
fi
ZSH_BIN=$(bash -c "which zsh")
[ "$(basename $SHELL)" != "zsh" ] && chsh -s $ZSH_BIN

echo "Will install files into $BASEDIR"

if [[ "$CLONE_REPO" -gt 0 ]]; then
  git clone https://github.com/mtxr/dotfiles.git $BASEDIR && \
  git -C $BASEDIR submodule update --init --recursive "${DOTBOT_DIR}"
fi

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" && \

exec $ZSH_BIN
