#!/usr/bin/env zsh


DOTBOT_DIR=".dotbot"

DOTBOT_BIN="bin/dotbot"
SCRIPTPATH=`realpath -s $0`
BASEDIR=$(dirname "${SCRIPTPATH}") # workstation path
CONFIG="${BASEDIR}/.install.conf.yaml"

git -C $BASEDIR submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

/usr/bin/env zsh
