#!/bin/bash

PIPE1='cat'
PIPE2='cat'

if [[ "$@" = *'--select'* ]] || [[ "$@" = *'-s'* ]];then
  PIPE1='fzf --header-lines=1'
fi

if [[ "$@" = *'--ip'* ]] || [[ "$@" = *'-i'* ]];then
  PIPE2="rg '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' -o --color never"
fi
if type ip &> /dev/null ; then
  ( echo 'Interface'$'\t''IP' && { \
    ip addr | \
    rg '\s*inet\s' -B2 | \
    rg '(^[0-9]+:\s*([A-Za-z0-9]+):.+|[ \t\s]*inet (\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}).*)' --replace '>>$2#$3' | \
    tr -d '\n' | \
    rg '#>>#' --replace $'\t\t' | \
    rg '^>>' --replace $'' | \
    rg '>>' --replace $'\n'
  } | column -s $'\t' -o $'\t' -c 2) | eval $PIPE1 | eval $PIPE2
else
  ( echo 'Interface'$'\t''IP' && { \
    ifconfig | \
    rg '^(([A-Za-z0-9]+):.+|[ \t]*inet (\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}).+)' --replace '$2'$'\t''$3' | \
    sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/ /g' | \
    rg '(\d)[ \t].(\w)' --replace '$1'$'\n''$2' | rg '^[A-Za-z0-9]+[ \t]*\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
  } | column -s $'\t' -c 1 ) | eval $PIPE1 | eval $PIPE2
fi
