#!/bin/bash

ADDRESS='localhost'
FILENAME=/dev/stdout

usage () {
  cat <<-EOF
		Usage: ncpaste [output_filename] [options]
		  Options:
		    -H, --host <hostname> Specify host or ip origin
        -host                 This menu

		  Examples:
		    Output to stdout:
		      $ ncpaste
		    Output to file:
		      $ ncpaste file.out
		    Redirect output:
		      $ ncpaste > file.out
		      $ ncpaste > /dev/null
		    Reading from remote server to stdout:
		      $ ncpaste -h 192.168.1.1
		    Piping:
		      $ ncpaste | grep 'string'
	EOF
}

for i in "$@"
do
case $i in
    -H=*|--host=*)
      ADDRESS="${i#*=}"
      shift # past argument=value
    ;;
    -H|--host)
      ADDRESS=""
      shift
    ;;
    *)
      if [ "$ADDRESS" = "" ]; then
        ADDRESS="$i"
      else
        FILENAME="$i"
      fi
    ;;
esac
done

(nc "$ADDRESS" 13338 | pv -b > "$FILENAME") || ( usage )
