#!/bin/bash

PIPE1='cat'
PIPE2='cat'

if [[ "$@" = *'--select'* ]] || [[ "$@" = *'-s'* ]];then
  PIPE1='fzf --header-lines=1'
fi

if [[ "$@" = *'--ip'* ]] || [[ "$@" = *'-i'* ]];then
  PIPE2="rg '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' -o --color never"
fi

( echo 'Interface'$'\t''IP' && { \
  ifconfig | \
  rg '^(([A-Za-z0-9]+):.+|[ \t]*inet (\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}).+)' --replace '$2'$'\t''$3' | \
  sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/ /g' | \
  rg '(\d)[ \t].(\w)' --replace '$1'$'\n''$2' | rg '^[A-Za-z0-9]+[ \t]*\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
} | column -s $'\t' -c 1 ) | eval $PIPE1 | eval $PIPE2
