export TERM="xterm-256color"
export EDITOR=vim
export VISUAL=$EDITOR
export PAGER=less
export LESS='-F -g -i -M -R -S -w -X -z-4'
export WORDCHARS=''
export PROJECTS=$HOME/projects
export N_PREFIX="$HOME/.n"
export WORKSTATION=$HOME/.workstation
export PATH=$WORKSTATION/bin:$N_PREFIX/bin:$HOME/bin:/usr/local/sbin:$PATH
HISTSIZE=1048576
HISTFILE="$HOME/.zsh_history"
SAVEHIST=$HISTSIZE
