#!/bin/zsh

export TERM=${TERM:-screen-256color}
export EDITOR=vi
export VISUAL=$EDITOR
export PAGER=less
export LESS='-F -g -i -M -R -S -w -X -z-4'
export WORDCHARS=''
export PROJECTS=$HOME/projects
export GOPATH=$PROJECTS/go
export DOTFILES=$HOME/.dotfiles
export N_PREFIX=${N_PREFIX:-"$HOME/.n"}
export PATH="$DOTFILES/bin:$HOME/.yarn/bin:$N_PREFIX/bin:$HOME/.local/bin:$GOPATH/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$HOME/bin:/snap/bin:/usr/local/sbin:/sbin:$PATH"
export GIT_CLEAR_BRANCH_EXCLUDE="release|develop|master|development|staging"
export fpath=( $HOME/.autoload-zsh $DOTFILES/rcfiles/zsh/functions/completions $fpath )
export VSCODE_FILE=$HOME/.vscode-cli
export GPG_TTY=$(tty)
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow -g "!{.git,node_modules}/*" 2> /dev/null'
export PKG_CONFIG_PATH="/usr/lib/x86_64-linux-gnu/pkgconfig/:/usr/share/pkgconfig:/usr/lib/pkgconfig:$PKG_CONFIG_PATH"
export JAVA_HOME="/usr/java/latest"
export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
export HOMEBREW_NO_AUTO_UPDATE=1
export LANG=en_US.UTF-8
export LANGUAGE=$LANG
export LC_ALL=$LANG

HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000
SAVEHIST=$(($HISTSIZE * 1.5))
WORKSTATION_AUTOUPDATE=true

setopt APPEND_HISTORY
setopt AUTO_CD
setopt AUTO_LIST
setopt AUTO_MENU
setopt ALWAYS_TO_END
setopt CORRECT_ALL
setopt EXTENDED_GLOB
setopt EXTENDED_HISTORY
setopt GLOB_DOTS
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_NO_STORE
setopt HIST_REDUCE_BLANKS
setopt HIST_VERIFY
setopt INC_APPEND_HISTORY
setopt INTERACTIVE_COMMENTS
setopt LIST_TYPES
setopt LONG_LIST_JOBS
setopt MENU_COMPLETE
setopt NO_BEEP
setopt NO_HUP
setopt NOTIFY
setopt NULL_GLOB
setopt PROMPT_SUBST
setopt SHARE_HISTORY

# Initialize completion
autoload -Uz compinit
autoload -Uz bashcompinit

if [ -e ~/.zcompdump ] && [ $(date +'%Y%j') != $(date +'%Y%j' -r ~/.zcompdump) ]; then
  compinit -i
  bashcompinit
else
  compinit -i -C
  bashcompinit -C
fi

# Aliases
. $HOME/.zsh/aliases.zsh

# Functions
. $HOME/.zsh/functions.zsh