. $HOME/.zsh/env.zsh

# command -v tmux &>/dev/null \
#   && [ -z $TMUX ] \
#   && [[ ! "$TERM_PROGRAM" =~ vscode ]] \
#   && exec tmux -2

# Bootstrap
. $HOME/.zsh/bootstrap.zsh

# External plugins (initialized before)
. $HOME/.zsh/plugins_before.zsh

# External settings
. $HOME/.zsh/external.zsh

# Aliases
. $HOME/.zsh/aliases.zsh

# External plugins (initialized after)
. $HOME/.zsh/plugins_after.zsh

# Functions
. $HOME/.zsh/functions.zsh

# Allow local customizations loading ~/.zsh-load folder
if [ -d "$HOME/.zsh-load" ];then
  for TO_LOAD in $HOME/.zsh-load/*
  do
    . $TO_LOAD
  done
  unset TO_LOAD
fi

. $HOME/.zsh/autoupdate.zsh


export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# Need a tweak in arch for home and end keys to work properly
# (as well as insert, delete, pageup, pagedown, perhaps others...)
# https://wiki.archlinux.org/index.php/Home_and_End_keys_not_working#Zsh
bindkey "^[[2~" overwrite-mode # Ins
bindkey "^[[3~" delete-char # Del

# but.... home and end key escape sequences
# are DIFFERENT depending on whether I'm in a tmux session or not!
# To determine if tmux is running, examine values of $TERM and $TMUX.
if [[ "$TERM" =~ "screen" ]] && [ -n "$TMUX" ]; then
  bindkey "^[[1~" beginning-of-line
  bindkey "^[[4~" end-of-line
else
  # Assign these keys if tmux is NOT being used:
  bindkey "^[[H" beginning-of-line
  bindkey "^[[F" end-of-line
fi