#!/bin/bash

# This way you can customize which branches should be skipped when
# prepending commit message.
if [ -z "$BRANCHES_TO_SKIP" ]; then
  BRANCHES_TO_SKIP=(massster develop main dev)
fi

BRANCH_NAME=$(git symbolic-ref --short HEAD)
BRANCH_NAME="${BRANCH_NAME##*/}"

BRANCH_EXCLUDED=$(printf "%s\n" "${BRANCHES_TO_SKIP[@]}" | grep -c "^$BRANCH_NAME$")

if [[ $BRANCH_EXCLUDED -eq 1 ]]; then
  exit 0
fi

if [[ $(grep -c "\[$BRANCH_NAME\]" $1) -eq 1 ]] || [[ $(grep -c "$BRANCH_NAME *:" $1) -eq 1 ]]; then
  exit 0
fi

if [[ "$BRANCH_NAME" =~ ^[a-zA-Z0-9]+-[0-9]+ ]]; then
  sed -i.bak -e "1s/^/[$BRANCH_NAME] /" $1
fi